/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */


CREATE TABLE student (
  `number` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL ,
  `name` varchar(30) NOT NULL,
  firstName varchar(30) NOT NULL,
  adress varchar(100) NOT NULL,
  phoneNumber varchar(10) NOT NULL,
  mail varchar(50) NOT NULL,
  birthday date NOT NULL,
  gender tinyint(4) NOT NULL,
);

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
